Repository FireGutter/geneference, pull requests merged in 2021-05, with the labels that each got.

#2 Linting and documenting some of the functions
  R/Testsim.R
  R/cov_tester.R
  R/covmatrix.R
  R/create_map.R
  R/family_simulation.R
  R/rmnorm.R
  man/cov_tester.Rd
  man/covmatrix.Rd
  man/create_map.Rd
  man/family_simulation.Rd
  man/rmnorm.Rd
  man/testsim.Rd
Labels: documentation

#3 Setup for pkgdown, changes to to_ped
  .Rbuildignore
  .github/workflows/pkgdown.yaml
  R/To_ped.R
  README.Rmd
  README.md
  man/figures/README-pressure-1.png
  man/figures/logo.png
  man/to_ped.Rd
Labels: documentation

#4 Changes related to pkgdown
  .github/workflows/pkgdown.yaml
  DESCRIPTION
  NAMESPACE
  R/Testsim.R
  R/To_ped.R
  R/calculate_cov.R
  R/covmatrix.R
  R/create_map.R
  R/data.R
  R/family_simulation.R
  R/rmnorm.R
  README.Rmd
  README.md
  _pkgdown.yml
  man/calculate_cov.Rd
  man/covmatrix.Rd
  man/create_map.Rd
  man/data_for_testsim.Rd
  man/family_simulation.Rd
  man/rmnorm.Rd
  man/testsim.Rd
  man/to_ped.Rd
  vignettes/gibbs.Rmd
Labels: documentation

#8 Updating web page, adding vignettes
  DESCRIPTION
  README.Rmd
  README.md
  _pkgdown.yml
  vignettes/geneference.Rmd
  vignettes/gibbs.Rmd
  vignettes/liability-distribution.Rmd
Labels: documentation

#10 Input validation
  R/Testsim.R
  R/calculate_cov.R
  R/covmatrix.R
  R/family_simulation.R
  R/individualsim.R
  R/rmnorm.R
Labels: enhancement

#11 Adding the simulation functions to the generfernce package
  NAMESPACE
  R/family_dist_simulaiton.R
  R/family_simulation.R
  R/randomized_familiy_simulation.R
  man/family_dist_simulaiton.Rd
  man/randomized_familiy_simulation.Rd
Labels: enhancement

#13 Change k to j
  R/family_dist_simulaiton.R
  R/family_simulation.R
Labels: enhancement

#15 Change the imports
  NAMESPACE
  R/Gibbs_sampler.R
  R/Testsim.R
  R/assign_phenotypes.R
  R/calculate_cov.R
  R/create_map.R
  R/family_dist_simulaiton.R
  R/family_simulation.R
  R/individualsim.R
  R/randomized_familiy_simulation.R
  R/rmnorm.R
  R/utils-pipe.R
  man/pipe.Rd
Labels: enhancement

#18 Implementation plots, data manipulation
  DESCRIPTION
  NAMESPACE
  R/Testsim.R
  R/error_types.R
  R/family_dist_simulaiton.R
  R/family_simulation.R
  R/load_data.R
  R/plink_calls.R
  R/randomized_familiy_simulation.R
  R/visualisations.R
  _pkgdown.yml
  man/calculate_error_types.Rd
  man/family_dist_simulaiton.Rd
  man/family_simulation.Rd
  man/load_assoc_results.Rd
  man/load_phenotypes.Rd
  man/plot_estimates_vs_true.Rd
  man/plot_manhattan.Rd
  man/plot_pmgl_vs_true.Rd
  man/plot_pval_QQ.Rd
  man/plot_pval_hist.Rd
  man/randomized_familiy_simulation.Rd
  man/testsim.Rd
Labels: enhancement

#26 Gibbs
  R/Gibbs_sampler.R
  R/assign_phenotypes.R
Labels: documentation

#27 Pmgl assigment
  R/assign_phenotypes.R
  R/calculate_cov.R
  R/n_sibs.R
  man/assign_GWAX_phenotype.Rd
  man/assign_ltfh_phenotype.Rd
  man/calculate_cov.Rd
  man/n_sibs.Rd
Labels: enhancement

#28 Testing
  R/Testsim.R
  R/family_dist_simulaiton.R
  R/family_simulation.R
  R/individualsim.R
  R/path_validation.R
  R/rmnorm.R
  man/family_simulation.Rd
  man/rmnorm.Rd
  tests/testthat/test-covmatrix.R
  tests/testthat/test-family_simulation.R
  tests/testthat/test-individualsim.R
  tests/testthat/test-rmnorm.R
Labels: bug, enhancement

#31 Input validation
  R/assign_phenotypes.R
  R/calculate_cov.R
  R/covmatrix.R
  R/error_types.R
  R/load_data.R
  R/plink_calls.R
  R/rmnorm.R
  R/sim_fixed_family.R
  R/sim_no_family.R
  R/sim_random_family.R
  R/sim_test.R
  R/sim_varied_family.R
  R/visualisations.R
Labels: documentation

#33 Spaces and plink
  R/plink_calls.R
  R/quote_path.R
  man/analysis_association.Rd
  man/analysis_lasso.Rd
  man/p_2_b.Rd
  man/plot_pval_QQ.Rd
Labels: bug, documentation

#34 Loader
  NAMESPACE
  R/load_data.R
  R/visualisations.R
  man/Compare_beta.Rd
  man/mutator.Rd
  man/reader.Rd
Labels: enhancement

#35 moved the "&&" to the right place
  R/plink_calls.R
Labels: enhancement

#36 Final version of Gibbs vignette
  man/figures/gibbs-pseudo.png
  vignettes/geneference.Rmd
  vignettes/gibbs.Rmd
Labels: documentation

#37 Plot pmgl
  DESCRIPTION
  R/visualisations.R
Labels: enhancement

#38 Liability vignette
  vignettes/gibbs.Rmd
  vignettes/liability-distribution.Rmd
Labels: documentation

#39 Plot
  R/visualisations.R
  man/Compare_beta.Rd
  man/plot_estimates_vs_true.Rd
  man/plot_manhattan.Rd
  man/plot_pmgl_vs_true.Rd
  man/plot_pval_QQ.Rd
  man/plot_pval_hist.Rd
Labels: enhancement

#41 Documenting all functions
  NAMESPACE
  R/Gibbs_sampler.R
  R/assign_phenotypes.R
  R/calculate_cov.R
  R/covmatrix.R
  R/error_types.R
  R/load_data.R
  R/plink_calls.R
  R/rmnorm.R
  R/sim_fixed_family.R
  R/sim_no_family.R
  R/sim_random_family.R
  R/sim_test.R
  R/sim_varied_family.R
  R/visualisations.R
  _pkgdown.yml
  man/Compare_beta.Rd
  man/analysis_association.Rd
  man/analysis_lasso.Rd
  man/assign_GWAX_phenotype.Rd
  man/assign_ltfh_phenotype.Rd
  man/augment_results.Rd
  man/calculate_cov.Rd
  man/calculate_error_types.Rd
  man/convert_geno_file.Rd
  man/covmatrix.Rd
  man/load_assoc_results.Rd
  man/load_phenotypes.Rd
  man/load_results.Rd
  man/mutator.Rd
  man/p_2_b.Rd
  man/plot_estimates_vs_true.Rd
  man/plot_manhattan.Rd
  man/plot_pmgl_vs_true.Rd
  man/plot_pval_QQ.Rd
  man/plot_pval_hist.Rd
  man/reader.Rd
  man/rmnorm.Rd
  man/sim_fixed_family.Rd
  man/sim_no_family.Rd
  man/sim_random_family.Rd
  man/sim_test.Rd
  man/sim_varied_family.Rd
  vignettes/gibbs.Rmd
Labels: bug, documentation
