Repository FireGutter/geneference, pull requests merged in 2021-06, with the labels that each got.

#40 Sim vignette
  DESCRIPTION
  _pkgdown.yml
  man/compare_beta.Rd
  vignettes/sim-benchmarks.Rmd
Labels: documentation

#42 Test
  R/error_types.R
  R/plink_calls.R
  R/visualisations.R
  man/calculate_error_types.Rd
  man/plot_estimates_vs_true.Rd
Labels: bug, documentation, enhancement

#43 Finished intro vignette, polished
  DESCRIPTION
  R/assign_phenotypes.R
  R/sim_test.R
  README.Rmd
  README.md
  _pkgdown.yml
  man/assign_ltfh_phenotype.Rd
  man/figures/gibbs-plottest-1.png
  man/figures/intro_beta-comp.png
  man/figures/intro_calcov.png
  man/figures/intro_errtbl.png
  man/figures/intro_manhattan.png
  man/figures/intro_phist.png
  man/figures/intro_pmgl.png
  man/figures/intro_pqq.png
  man/sim_test.Rd
  vignettes/geneference.Rmd
  vignettes/liability-distribution.Rmd
  vignettes/sim-benchmarks.Rmd
Labels: bug, documentation

#44 Fixed some indexes in the scopes
  R/sim_fixed_family.R
  R/sim_varied_family.R
Labels: enhancement

#45 Corrected some small things
  R/plink_calls.R
  R/sim_fixed_family.R
  R/sim_no_family.R
  R/sim_test.R
  R/sim_varied_family.R
Labels: enhancement
